# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "f97c5bebfd0ca3b8d6c7793888f09ef3"
name = "SE Product Options"
application_url = "https://se-product-options-q7ghcsuwc-saad-eshops-projects.vercel.app"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_themes,write_publications,write_cart_transforms,write_files,read_files"

[auth]
redirect_urls = [ "https://se-product-options-q7ghcsuwc-saad-eshops-projects.vercel.app/auth/callback", "https://se-product-options-q7ghcsuwc-saad-eshops-projects.vercel.app/auth" ]

[app_proxy]
url = "https://se-product-options-q7ghcsuwc-saad-eshops-projects.vercel.app/"
subpath = "se-product-options"
prefix = "apps"
